### ISSUE TITLE
按照指示开启SWAGGER_ENABLE后无法看到文档页面

### ISSUE THREAD

**Issue by willow-god** [kingwrcy/moments#210]
您好老哥，感谢您的项目，我想使用这个项目替换memos，看到您说有了API，感觉可以通过请求api获取数据并展示到前端，所以过来试了一下，但是按照文档设置后好像看不到API文档页面，并且我尝试访问`/api/memo/get`好像也获取不到，请问是什么问题呀？

我的`docker-compose.yml`文件如下：

```yaml
version: '3'
services:
  moments:
    image: kingwrcy/moments:latest
    environment:
      JWT_KEY: "adjhaaejdhsadskfaddasdhd"
      ENABLE_SWAGGER: true
    ports:
      - "3003:3000"
    volumes:
      - moments-data:/app/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
volumes:
  moments-data:
```

我部署的页面地址如下：[mm.liushen.fun](https://mm.liushen.fun/)，麻烦老哥帮忙看一下，谢谢！
