### ISSUE TITLE
修改上传图片之间的缝隙间距

### ISSUE THREAD

**Issue by Apicer** [kingwrcy/moments#216]
![image](https://github.com/user-attachments/assets/e2f1ebc3-72ee-469a-99ee-67b67af251a5)

![image](https://github.com/user-attachments/assets/1be50b5b-e37c-4225-a555-2a0df50c3be1)

第一张图是微信截取的九宫格图片，九张图的间距很小，第二张是上传图片后的，每张图片间距很大，我在调试里设置了gap的参数可以展示和微信一样的间距。修改设置里的CSS样式能否修改，如果可以的话能给个CSS样式代码吗？

**Comment by xuewenG** [comment]
这个间距具体多大要看个人的喜好，如果你想调整的话，可以试试下面的自定义样式代码。

根据最新的 dev 代码(1aee952)编写，没有测试 v0.2.6 的代码。后续代码变更时，也可能会失效。如果没效果的话，按照这个思路修改一下就行。需要浏览器支持 `:has` 选择器，兼容性见 [can-i-use-css-has](https://caniuse.com/css-has)：

```css
div:has(> .full-cover-image-mult) {
  gap: 0.05rem !important;
}

div.grid.gap-2:has(> div.relative) {
  gap: 0.05rem !important;
}
```
